### ISSUE TITLE
Laravel: use Facade alias versus Fully-Qualified Class Name

### ISSUE THREAD

**Issue by Haru0** [Selectra-Dev/standards#10]
I normally remove that facade namespace, do you think its more readable ?

_Originally posted by @tomasbotellacanto in https://github.com/Selectra-Dev/blanco/pull/20_

**Comment by Haru0** [comment]
@tomasbotellacanto or @rbsteiner Could you please redact this issue and assign all the backed devs to it?

**Comment by rbsteiner** [comment]
Laravel uses aliases in config/app.php
`use Config;` 
is the same as 
`use Illuminate\Support\Facades\Config;`

**Comment by rbsteiner** [comment]
https://www.sitepoint.com/how-laravel-facades-work-and-how-to-use-them-elsewhere/

**Comment by Mexidense** [comment]
From my point, I prefer use full namespace because maybe exists a class with same name of the other library o vendor... it's difficult to find that match but for avoid conflict names: I prefer use full namespace too.

**Comment by Eighke** [comment]
> Laravel uses aliases in config/app.php
> `use Config;`
> ~~is~~ **may be** the same as
> `use Illuminate\Support\Facades\Config;`

Fixed. It's not exactly the same, the alias may not be registered for some reason (or as @Mexidense said it may be linked to another library).

For a project it is the same because you manage the `config/app.php` (I personally use the alias). But alias should never be used in a library/package.

**Comment by JesusValera** [comment]
> > Laravel uses aliases in config/app.php
> > `use Config;`
> > ~is~ **may be** the same as
> > `use Illuminate\Support\Facades\Config;`
> 
> Fixed. It's not exactly the same, the alias may not be registered for some reason (or as @Mexidense said it may be linked to another library).
> 
> For a project it is the same because you manage the `config/app.php` (I personally use the alias). But alias should never be used in a library/package.

There is a full namespace for all facades.
You can find the real path here: https://laravel.com/docs/5.8/facades#facade-class-reference


Config | *Illuminate\Config\Repository* | `config`
-- | -- | --

**Comment by Haru0** [comment]
I don't use facades for production code. Sometimes, when I'm testing/prototyping something I might use it temporarily but I always try to remove it from the final version.

I'm always putting FQCN because I want all the classes to be pointed explicitly. Thanks to this approach: 
- I have autocompletion always working (without any assistance like ide-helper) without any effort
- It's less cryptic - possibility to use facades with short names is another abstraction layer

However, I think there is one place I'd encourage using facades - this would be blade templates.

**Comment by Mexidense** [comment]
I agree with you @Haru0 
Then, we could use FQCN in logic layer of app and in view layer use Facades? 

Anyone else want to share his view point?

**Comment by ibeona** [comment]
I have the habit to use the facade because it's faster and use only the one registered in config/app.php so i'm sure of the one I use as the mapping already exists and it's up to the dev to decide the link between the facade and the class to use in config file.
This is for project side. 
But for library/package it must be FQCN as said @Eighke because we don't have the context of the package.

**Comment by Haru0** [comment]
It would be nice to have one final decision. We have more versatility using FQCNs. Could we agree on this or there are more people using aliases? @tristanjahier @tomasbotellacanto

**Comment by tomasbotellacanto** [comment]
I agree using FQCNs :)

**Comment by Eighke** [comment]
> It would be nice to have one final decision. We have more versatility using FQCNs. Could we agree on this or there are more people using aliases? @tristanjahier @tomasbotellacanto

We should stop using FQCN, people are mixing all the term.

* Facade (e.g. `Illuminate\Support\Facades\Config`)
* Alias (e.g. `Config`)
* Singleton/Bind (e.g. `Illuminate\Config\Repository`)

So for example when @Mexidense say FQCN in app and Facades in view, is it about Singleton in app and Facades in view? Or Facades in app and Alias in view? Or Signeton in app and Alias in view?~;

**Comment by Mexidense** [comment]
> > It would be nice to have one final decision. We have more versatility using FQCNs. Could we agree on this or there are more people using aliases? @tristanjahier @tomasbotellacanto
> 
> We should stop using FQCN, people are mixing all the term.
> 
> * Facade (e.g. `Illuminate\Support\Facades\Config`)
> * Alias (e.g. `Config`)
> * Singleton/Bind (e.g. `Illuminate\Config\Repository`)
> 
> So for example when @Mexidense say FQCN in app and Facades in view, is it about Singleton in app and Facades in view? Or Facades in app and Alias in view? Or Signeton in app and Alias in view?~;
I mean Facades (with FQCN) in app and Alias in view

**Comment by JesusValera** [comment]
I even prefer to use the FQCN in both places (logic and view), but if you prefer to put the facade alias in the view, np.
But I strongly disagree to use alias in the code...

**Comment by rbsteiner** [comment]
I really don't have any opinion about this. If we are inside Laravel scope, why not, but as others pointed out, FQCN makes working with IDEs easy etc etc...
IMHM is more important to be committed with whatever choice was made in a project and it is not always the case.
If everyone is Ok with put FQCN as mandatory I'm in nothing against that... Go with the flow :)

**Comment by tristanjahier** [comment]
I personnally use aliases for facades. I've always done that because I felt like facades were designed to be used like this. Then I've not thought much about it.

I think conflicts would be extremely rare because 3rd party packages should provide classes inside of a dedicated namespace (not the global one). Also, if a Laravel package provides a facade, it is up to you to define an alias in `config/app.php`, and you are supposed to know what you are doing.

**Comment by Eighke** [comment]
> FQCN makes working with IDEs easy

Well in the same time without ide helper for Laravel many thing is missing anyway. Most Facades don't implement all `@method` and it will miss some in the IDE, not even speaking about 3rd party Facade that usually have none.

The worst could be that miss some method because they are not ref. So it may make it more hard than easy in some case. ^^;

**Comment by Haru0** [comment]
Opinions are distributed evenly. 

I'm closing this issue leaving this to the developer. I can't find an **essential** argument for or against using FQCN. From one side I've never encountered a problem with using FQCN, from the other, we always use ide-helper and our code is never taken outside Laravel.

What is assumed:
- You're allowed to use whatever you prefer more - FQCN or alias
- Don't use aliases in packages and portable code (framework agnostic packages, we will never share controllers between frameworks)
- Try to avoid facades [example ref](https://programmingarehard.com/2014/01/11/stop-using-facades.html/)
- [Prefer dependency injection over facades as already told in standards](https://github.com/Selectra-Dev/standards/blob/88f1b5835e3f34dc916b0d0ceb45d3665fca50a7/programming/LARAVEL.md#L14)
