### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by Mexidense** [Selectra-Dev/standards#11]
Hi guys!

From my ignorance...

Question is simple: **What Git workflow are Selectra using?** 

Some references:
https://www.atlassian.com/git/tutorials/comparing-workflows
https://guides.github.com/introduction/flow/
https://itnext.io/the-github-development-workflow-fb48d9bb63f9

Thank you!

Regards!

cc @theosuja @wilsonelwilson @juanjo698 @elodieanthony @thsgithub  ... (I don't know if someone is missing)

**Comment by Haru0** [comment]
[git-flow](https://danielkummer.github.io/git-flow-cheatsheet/) FTW! (I think Spanish team is using it)

Also, we have a separate document for that [here](https://github.com/Selectra-Dev/selectra-standards/blob/master/project-management/github.md).

IMO, the weakest point in the current approach is in making master branch not production but development.

Problem is with current Semaphore setup. I really would like to have them following git-flow, but changing them all will need @VictorBersy to spend a lot of time doing that. I don't want to bother him on such unproductive thing.

**Comment by Eighke** [comment]
I'd say: it depends of many criteria. 

How is shipped the project? Is it already released? Is it a project or a lib? On lib, do you have to maintain the old versions? :)

But will I like git-flow for project. Not sure if it's the best for lib (per issue branch may be better? especially if you don't maintain old versions).

**Comment by VictorBersy** [comment]
Ideally, `production` and `staging` branches will be removed and only releases/tags will be used for deployments. I'm planning to do all of that during migration to Semaphore 2.0, that will allow us to use releases as deployment triggers, something that is not possible right now on Semaphore.

**Comment by Haru0** [comment]
ETA?

**Comment by VictorBersy** [comment]
No ETA but you can subscribe to this task to be informed https://3.basecamp.com/3797456/buckets/11724544/todos/1731415398

**Comment by Haru0** [comment]
I'll do that. Thanks!

**Comment by Haru0** [comment]
Let's rediscuss this once Semaphore gets updated. [GITHUB.md](https://github.com/Selectra-Dev/standards/blob/69a364c1ad02605fab85e0d13d7fac6cec3a9ca7/management/GITHUB.md) is considered outdated and will also be updated in the future.

What's assumed:
- The workflow needs to be unified across our projects - **git-flow** seems to be the best candidate
- Using `production` instead of `master` branches is misleading/confusing. `Master` branch shouldn't be considered `development`.
