### ISSUE TITLE
Rename repository to Selectra-Dev/selectra-standards

### ISSUE THREAD

**Issue by Haru0** [Selectra-Dev/standards#12]
I think there's no reason to put "selectra" in the repository name twice. Let's simplify this name to `Selectra-Dev/standards`.

Or maybe it would be better to have separate repositories for programming (or even more detailed - php, ruby, etc.) and management?

**Comment by Haru0** [comment]
@Selectra-Dev/developers

**Comment by JesusValera** [comment]
@Haru0 Do you mean to rename to: `Selectra-Dev/standards`?

**Comment by Haru0** [comment]
Yes, my bad. Description updated.

**Comment by JesusValera** [comment]
> Yes, my bad. Description updated.

Yes, I agree with you.
I think is cleaner without `selectra` word in the project title.

**Comment by Mexidense** [comment]
:+1:  Selectra-Dev/standards

**Comment by VictorBersy** [comment]
👍
Do you have the permission to do it?

**Comment by Haru0** [comment]
No. I've assigned @tristanjahier to do that.

**Comment by VictorBersy** [comment]
He has the same set of permissions that you do. I think you need to be admin to rename a repository. I will rename it.

**Comment by VictorBersy** [comment]
:boom: renamed
