### ISSUE TITLE
Reference front-end standards

### ISSUE THREAD

**Issue by Haru0** [Selectra-Dev/standards#14]
If I remember correctly, there is a document you guys are using for front-end standards. Could somebody please reference it in the right section?

**Comment by crisisinaptica** [comment]
@Haru0 We are working on having [this site](https://selectra.design/) ready for the DS 1.0 release.

So, maybe it's just a matter of just dropping a link and a minimal explanation on a `selectra-standards/programming/front-end/ds-docs.md` file ?

**Comment by Haru0** [comment]
Yes. This is exactly what I'm looking for, but you might also use this file for more detailed standards if you want. 
Could you please create a PR for that?

**Comment by crisisinaptica** [comment]
Nice to know, but don't expect much content here until we finish the DS docs though... :/
I'll note this in my TODO list.

**Comment by Mexidense** [comment]
:eyes:
