### ISSUE TITLE
Remove unnecesary comments?

### ISSUE THREAD

**Issue by JesusValera** [Selectra-Dev/standards#18]
Hi guys,
I was working on a project and I saw this piece of code:

```php
/**
 * @param string $countryCode
 * @param BoilerTypesResolver $resolver
 */
public function __construct(string $countryCode, BoilerTypesResolver $resolver)
{
    $this->country = $countryCode;
    $this->resolver = $resolver;
}

/**
 * @return array
 */
public function transform(): array
{
    list($old, $new) = $this->resolver->resolve();

    return [
        AccommodationInterface::BOILER_AGE_OLD => trans('general.attributes.blabla'),
        AccommodationInterface::BOILER_AGE_MID => trans('general.attributes.blabla'),
        AccommodationInterface::BOILER_AGE_NEW => trans('general.attributes.blabla'),
    ];

}
```

I strongly agree with the use of comments but sometimes I feel they can be more annoyed than useful.
The point is when you are documenting only the `@params` & `@return`, I think is better if we rid out that piece of comment for the shake of simplicity.

I also think that put comments like those is even worse and it messes the whole class up.
```php
/**
 * Build though the constructor method the class.
 *
 * @param string $countryCode
 * @param BoilerTypesResolver $resolver
 */
public function __construct(string $countryCode, BoilerTypesResolver $resolver)
{
    //
}

/**
 * This method transforms some trans keys depending on the application language.
 *
 * @return array
 */
public function transform(): array
{
    //
}
```

So, I proposed to do not use comments in this kind of places.

```php
public function __construct(string $countryCode, BoilerTypesResolver $resolver)
{
    //
}

public function transform(): array
{
    //
}
```

What do you think?

I am glad to hear from you. :smile:

**Comment by JesusValera** [comment]
I think I have included all back-end devs, if you miss someone, do not hesitate to mention him/her. :)

**Comment by Mexidense** [comment]
IMHO, I think if you need to comment code, it's bad code... but in that case, those examples are phpdoc blocks and it's a documentation and I think that it's really necessary... obvious but necessary...

**Comment by rbsteiner** [comment]
I use this kind of annotations when I want to generate Automated documentation... 
https://www.phpdoc.org/
http://www.phpdoc.de/
http://www.doxygen.nl/

**Comment by Haru0** [comment]
I think the question is about "empty" comments (those documenting only parameters and return type and saying basically what method name say - like `/** A "foo" property getter. */ function getFoo() {}`).

- I'm using PhpStorm, it handles no docs fairly well. I don't know how other IDEs are behaving, so **I always put** such doc-blocs.
- Documentation tools like phpDocumentor (or any of those Ramon mentioned), most of the times, handles them properly, but I like **to be sure** it makes no mistake.
- I **avoid** commentary (not type hinting and return types or exceptions thrown) when a method is self-explanatory. Sometimes when I generate getters/setters with PHPStorm they might persist (but anyway, this is a template you can edit and remove it).

I use them for my own security and code consistency. **PHP is a weakly-typed language**. If it wasn't we wouldn't have this problem. In my opinion, it should be recommended. If comments are annoying you can always make your IDE [fold them](https://www.jetbrains.com/help/rider/Code_Folding.html) every time you open a file.

**Comment by Eighke** [comment]
@Haru0 PhpStorm currently handles no docs very well (it's probably the best IDE for that). Maybe your version is old?

So, IMO

* If the method is oblivious by it name, doesn't need special example, and doesn't have thing that need phpDocs (e.g. Throw Error, Mixed return, etc). The last example is the best.
* If it need special phpDocs, but the method still oblivious, the first example is the best.
* If the method is not oblivious, the second example is the best.

Just one last thing: phpDocs **are not** comments. :)

**Comment by Haru0** [comment]
> @Haru0 PhpStorm currently handles no docs very well (it's probably the best IDE for that). Maybe your version is old?

Indeed, I updated it recently but don't have any opinion yet. Anyway, you need to type hint them to work smoothly (we don't really do that everywhere).

> Just one last thing: phpDocs **are not** comments. :)

Good point @Eighke! I think we missed that from the beginning.

Can we sum up this?

- Comments are unnecessary for self-explanatory methods. Let's remove them. If you're commenting something you should check it twice if the design is correct.
- Annotations (phpdocs) are recommended. When type hints are not applied annotations are mandatory (?). We can avoid them when a method has no commentary and type hints ae applied (?). 

I'd also like to make it mandatory that if comment exist annotations have to be added too.

**Comment by JesusValera** [comment]
@Haru0, I guess you updated your PHPStorm version, what is going on with the documentation?
I still think we should remove this kind of comments from the code, it is not necessary at all...

**Comment by Haru0** [comment]
> I'm considering introducing phpstan/phpstan to our development. They have some nice features we could include to our standards (documenting array internal structure).

We will get back to this. But for now, I consider phpdocs optional when arguments are type-hinted. If you expect your argument to be of any type you have to put phpdoc (for example `/** @param  string|int|array $foo */`).

What's worth mentioning (and is mine preference only), I put them everywhere to keep consistency with the rest of codebase. The method having docblock seem to be complete (cherry on top of the cake). I don't really mind ignoring it when the method is properly defined.
