### ISSUE TITLE
Laravel migrations naming convention

### ISSUE THREAD

**Issue by Mexidense** [Selectra-Dev/standards#19]
Hi guys!

From this PR, I emerged a question about Laravel migration naming convention...

what is the patter for create a new migration in a project? 
e.g.
when I..:

create a new table:

`php artisan make:migration create_tableName_table`

add a new column: 

`php artisan make:migration add_columnName_to_tablename_table`

update a column like rename column:

`php artisan make:migration update_columnName_to_tablename_table`

remove a column:

`php artisan make:migration remove_columnName_from_tablename_table`

drop a table:

`php artisan make:migration drop_tableName_table`

is it right way?

I was researching at Illuminate\Database\Console\Migrations\TableGuesser and there're two patters for creating and changes.. 

```
const CREATE_PATTERNS = [
        '/^create_(\w+)_table$/',
        '/^create_(\w+)$/',
    ];

    const CHANGE_PATTERNS = [
        '/_(to|from|in)_(\w+)_table$/',
        '/_(to|from|in)_(\w+)$/',
    ];
```
thank you for your time :D

----------------------------------------------------------
`database/migrations/2019_07_26_102550_remove_zoho_sandbox_id_from_call_owners_table.php`

```php
class RemoveZohoSandboxIdFromCallOwnersTable extends Migration
{
```
For example?

That is the idea.

_Originally posted by @JesusValera in https://github.com/Selectra-Dev/blanco/timeline_

**Comment by Eighke** [comment]
For a project? Only the permanent `create_tablename_table` is really important. But the rest is correct.

It's just that on a project you will usually also add the changes to the permanent `create_x` and then you can drop update files after the production deployment.

This way you can easily see your database scheme without having to install the project, or check 50 update files.

**Comment by JesusValera** [comment]
I agree with you @Eighke.
The topic here is like this kind of naming convention for migration has not been defined (or I have not been able to find it).
Alike when we create a table it is obvious: `create_tableName_table`
when we only want to remove a column for a table, what name do you think fits better: `remove_columnName{_from_tableName}_table` or just `update_tableName_table` is enough.

Thank you!

**Comment by Eighke** [comment]
If it's removed later, I'm using `update_x` where `x` is the sprint number. ;)

If it's not removed (e.g. in libraries):
- if it has many change in a row `update_tableName_table`
- if it's a single change `remove_columnName{_from_tableName}_table`

So all are correct, depending of the situation. :)

**Comment by Haru0** [comment]
I'm not convinced by `update_{sprint_number}`, but I understand this is more convenient to do sometimes. I don't mind if we agree to put an explanatory description in the phpdoc block.

- When should we do bulk / multiple changes in a single migration file?
- Should we separate changes to a single table?

**Comment by Mexidense** [comment]
> If it's removed later, I'm using `update_x` where `x` is the sprint number. ;)
> 
> If it's not removed (e.g. in libraries):
> 
> * if it has many change in a row `update_tableName_table`
> * if it's a single change `remove_columnName{_from_tableName}_table`
> 
> So all are correct, depending of the situation. :)

@Eighke I agree with you totally! 


> I'm not convinced by `update_{sprint_number}`, but I understand this is more convenient to do sometimes. I don't mind if we agree to put an explanatory description in the phpdoc block.

@Haru0 do you need a phpdoc block for explain the changes in a table? I think that with code it's explicable... 
` $table->dropColumn('column1'); `
` $table->renameColumn('fromName', 'toName'); `

I don't know....

**Comment by Haru0** [comment]
> @Haru0 do you need a phpdoc block for explain the changes in a table? I think that with code it's explicable...

Of course. If there are bulk changes it might be hard for another developer to know what's going on at first sight.

The only situation I'm not certain about is how to call **update table migrations ** when it happened multiple times.

**Comment by Haru0** [comment]
Please review @tristanjahier @Eighke @JesusValera @rbsteiner @ibeona @tomasbotellacanto @juanjo698

**Comment by tristanjahier** [comment]
I agree with the proposals. I use explicit and verbose file names like those.

When I need to do multiple changes at a time because they all serve the same purpose (feature change) and they cannot live separately (they all need to be "up" or "down" together otherwise the app cannot work properly), I still try to express what I am doing in the file name.

We already discussed a similar topic earlier.

**Comment by tristanjahier** [comment]
I found it! I was explaining my point of view here: https://github.com/Selectra-Dev/standards/pull/5#discussion_r182784551

**Comment by tomasbotellacanto** [comment]
I agree with Tristan https://github.com/Selectra-Dev/standards/pull/5#discussion_r182784551

**Comment by Haru0** [comment]
True. I think everybody agrees this is a single "update table" migration.

**Comment by JesusValera** [comment]
Yes,
I agree with all your comments.

I prefer do not specify the Trello ticket number in the commit because who knows if someday we change to Atlassian (for example).

About creating three different commits against one if we want to replace one column from one table to another, I completely agree about just creating one migration, it is like a transaction, is an atomic thing and cannot be split.

But I think we have lost the topic.

The question is if we want to create a migration that only removes a `foo` column from `bar` table.

What name do you think better suits:

`remove_foo_from_bar_table`
or
`update_bar_table`.

It is supposed the last way is the "official" and "recommended" but I prefer and see clever using the first approach.
What do you think?

Cheers!

**Comment by Haru0** [comment]
> I prefer do not specify the Trello ticket number in the commit because who knows if someday we change to Atlassian (for example).

We will most likely never export tickets from one to another. HIstorical tickets will be always on Trelllo.

> About creating three different commits [...]

You mean `migration`, correct?

> What do you think?

Isn't that mentioned already https://github.com/Selectra-Dev/standards/blob/master/programming/LARAVEL.md#migrations?

**Comment by JesusValera** [comment]
> > I prefer do not specify the Trello ticket number in the commit because who knows if someday we change to Atlassian (for example).
> 
> We will most likely never export tickets from one to another. HIstorical tickets will be always on Trelllo.
>

:+1: 

> > About creating three different commits [...]
> 
> You mean `migration`, correct?
> 
Yes, I mean that.

> > What do you think?
> 
> Isn't that mentioned already https://github.com/Selectra-Dev/standards/blob/master/programming/LARAVEL.md#migrations?

It is, I didn't see.

Ok, I will close this issue. 
All is done! :smile:
