### ISSUE TITLE
Trait names convention.

### ISSUE THREAD

**Issue by JesusValera** [Selectra-Dev/standards#21]
Hello guys.

@Mexidense @tomasbotellacanto @Haru0 and @me had a discussion about how to call a trait.
You can see it in the following link: https://github.com/Selectra-Dev/estimate-consumption-v2/pull/111#discussion_r313840361

The topic is;
there are two ways to call the trait,
1. In present adding `-trait` word at the end of the name.
2. In passive explaining what it does.

For example:
We have a trait which modifies a collection.
We can call it like:
1. `ModifyCollectionTrait`.
2. `ModifiesCollection`.

Another example:
We have a trait which implement `foo()` and `bar()` methods.
1. `FooBarTrait`.
2. `HasFooBar`.

Which one do you feel more comfortable? Do you have any other suggestion?

I also would like to remark Laravel uses the second approach.

:fireworks: :boxing_glove: :fireworks:

I am glad to hear from you. :)

**Comment by rbsteiner** [comment]
I don't have a strong opinion on this...
I like the use of the suffix traits, because I know in seconds that it is a trait...
But naming without suffix forces the developer to restrain methods inside traits around an unique function dictated by the name. Traits are inside a folder named traits, anyway...

PSR says: 
> Traits MUST be suffixed by Trait: e.g. Psr\Foo\BarTrait.

**Comment by tristanjahier** [comment]
I agree with @rbsteiner. Except for the PSR part: it is never mentionned in any PSR, this is from a "bylaw": https://www.php-fig.org/bylaws/psr-naming-conventions

I don't understand what "bylaws" are, TBH. But I don't think they are part of the standard recommandations. I just think this is their personal standards when they provide code implementations.

**Comment by Haru0** [comment]
I'm opting for the second option. It's also what Laravel does (actually, it mixes them both but with a majority of the second convention).

**Comment by Eighke** [comment]
I usually follow the convention of the used framework. So the second on Laravel.

> Traits are inside a folder named traits, anyway...

Not mandatory, Symfony usually use single folder (e.g. https://github.com/symfony/symfony/tree/4.4/src/Symfony/Contracts/Cache)

**Comment by Mexidense** [comment]
I would prefer to chose first option for detect if it's a class, interface, abstract class or Trait... (or any more design patters like repository or collection...).

However, if Laravel use his own convention name and it's the second option, we must use his naming convention... in that case, we should be called with adjective words like: `Notifiable, Dispatchable...`

**Comment by Haru0** [comment]
> I don't understand what "bylaws" are, TBH. But I don't think they are part of the standard recommandations. I just think this is their personal standards when they provide code implementations.

It seems for me to be a way to introduce new PSR's (if you want to contribute there).

After all. I guess the most secure and following-good-practices choice will be the second option. Let's do that the same way Laravel does.
