### ISSUE TITLE
Align spaces in the code?

### ISSUE THREAD

**Issue by JesusValera** [Selectra-Dev/standards#31]
# Update (new; please, revise and give me back your opinion in comments) :smile: 

Hello guys.
I asked you yesterday your opinion about alignment in PhpDocs, now, I would like to know also your opinion about alignment in arrays.
I forget to ask you at the same time.
Any way, what option do you think is better? :smile: 

- A)
```php
$optionA = [
    'key'                       => 'value1',
    'keyToLoooooooong'          => 'value2',
    'keyEvenLooooooooooooonger' => 'value3',
    'k'                         => 'value4',
];
```
or

- B)
```php
$optionB = [
    'key' => 'value1',
    'keyToLoooooooong' => 'value2',
    'keyEvenLooooooooooooonger' => 'value3',
    'k' => 'value4',
];
```

----

# OLD (already added to standards file)

I would like to know what do you prefer and why, and to reach if it is possible a standard among all of us.

I know that it is not very essential but, as you could have heard once, the best code is when you do not know who was the author, which means that all we should follow the same methodologies and pattern while coding.

So, my question is: What are you using and why and would you be able to change it in order to use all of us the same system? :small_airplane: 

```php
/**
 * @param $one The first parameter
 * @param int $two The second parameter
 * @param string $three The third parameter
 */
function foo($one, $two = 0, $three = "String"): void
{
}
```
or

```php
/**
 * @param        $one The first parameter
 * @param int    $two The second parameter
 * @param string $three The third parameter
 */
function foo($one, $two = 0, $three = "String"): void
{
}
```

Option 3 (PSR-5 and proposed by @ibeona)
```php
/**
 * @param        $one   The first parameter
 * @param int    $two   The second parameter
 * @param string $three The third parameter
 */
function foo($one, $two = 0, $three = "String"): void
{
}
```
Thank you! :+1:

**Comment by ibeona** [comment]
hello @JesusValera 
I see there is a draft for psr-5 about phpdoc (https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md) that will go on the same way that the 2nd version except that the explaination is also align too to follow the same logic between variable type spacing and variable name. 
So I would propose 
```
/**
 * @param        $one   The first parameter
 * @param int    $two   The second parameter
 * @param string $three The third parameter
 */
function foo($one, $two = 0, $three = "String"): void
{
}
```
It's maybe more readable but on pmf we use the first one because we don't have thing too much about it 😅

**Comment by Haru0** [comment]
Thank you for raising this topic.

If aligning then aligning both the variable and its description. I don't like the "between" version. Personally, I don't mind using any.

For readability improvement, I vote for the PSR proposal.

**Comment by Mexidense** [comment]
Me too, I like the @ibeona suggestion! it's clear and easily readable :heart:

**Comment by lord-enzo** [comment]
From an outsider perspective: I think @ibeona 's option is the best too!

**Comment by JesusValera** [comment]
@Haru0, should I add that to the standard, right?

**Comment by Haru0** [comment]
Yes please.

**Comment by JesusValera** [comment]
@tristanjahier @Eighke @Haru0 @Mexidense @ibeona @tomasbotellacanto @juanjo698 @miguelselectra

**Comment by Mexidense** [comment]
what's happened @JesusValera ?

**Comment by JesusValera** [comment]
> what's happened @JesusValera ?

Update issue.
Please, give me your feedback. :)

**Comment by Mexidense** [comment]
> > what's happened @JesusValera ?
> 
> Update issue.
> Please, give me your feedback. :)

https://github.com/Selectra-Dev/standards/issues/31#issuecomment-541009050 ?

**Comment by tomasbotellacanto** [comment]
Option B @JesusValera

**Comment by ibeona** [comment]
> Option B @JesusValera

same.

**Comment by miguelselectra** [comment]
B rules

**Comment by JesusValera** [comment]
As far I concern:
Option A: Salva (mexidense)
Option B: Tomas (tomasbotellacanto), Julie (ibeona), Miguel (miguelselectra), Jesus (JesusValera)
No response: Michal (Har0), Tristan (tristanjahier), Fréderic (Eighke)

**Comment by Eighke** [comment]
Same same, no preference

**Comment by Haru0** [comment]
No preference. I'm fine with both. What's more important for me is to use **one** notation across a single project. Not mix them both.

> Another idea is - what about aligning array values in the code but leave them unaligned in translation files?

**Comment by Mexidense** [comment]
I lost this battle but I'll win the war! :cry: :muscle: 

But it's interesting and import @Haru0 said!:

> What's more important for me is to use **one notation** across a single project. Never mix them both.
