### ISSUE TITLE
Yoda conditions

### ISSUE THREAD

**Issue by miguelselectra** [Selectra-Dev/standards#35]
Hi guys,
I decided open this issue to ask your opinion about yoda conditions. 
('value' === $variable) instead ($variable === 'value')

**Describe the ambiguity of given standard**
I've been told that it was a Selectra standard, but @tristanjahier give me his opinion about this and he prefer avoid use yoda because is 'harder to read'. I agree with him.
What is your opinion about this?

**Additional context**
https://en.wikipedia.org/wiki/Yoda_conditions

**Comment by tomasbotellacanto** [comment]
I also feel that yoda conditions are harder to read

**Comment by Mexidense** [comment]
I always used to code in Yoda conditions when I can! if you read before the value you can think about what you want to compare...

**Comment by Haru0** [comment]
> Yoda conditions were made to be easier to read.

They're not mentioned in standards at all. They're not a must and not a recommendation. I'd consider them as local agreement - depending on project contributors preferences.

**Comment by Eighke** [comment]
https://dev.to/greg0ire/why-using-yoda-conditions-you-should-probably-not

I completely agreed with this article.

**Comment by tristanjahier** [comment]
Hi Miguel!

I think it is a very good idea to create a discussion for a topic like that. Nice initiative! 👍

I would like to come back to this: 

> I've been told that it was a Selectra standard

It is a widespread industry standard, but I could not find it in our own standards:
https://github.com/Selectra-Dev/standards/blob/master/programming/PHP.md

**Comment by JesusValera** [comment]
I prefer using Yoda conditions.
They are less error-prone in situations when you have to deal if a variable is or not a `null`.
Also, it could be a bit harder to read at the beginning but when you get use to it, it is a piece of cake! :eyes:
