### ISSUE TITLE
API clients - Repository naming convention

### ISSUE THREAD

**Issue by Haru0** [Selectra-Dev/standards#8]
From time to time, when we need to integrate external service, we need to implement an API client. Usually, it ends up with and minimalistic library that holds the logic responsible for connecting with the endpoints, preparing requests and processing responses.

> One essential thing about those libraries - they're framework-agnostic (not language-agnostic, that's why they have language/technology in the repository name). We can use them anywhere we want. They shouldn't hold anything related to any framework.

I've noticed we have two ways of naming those repositories and it would be nice if we could unify this. Please share your opinion, how should we make them all consistent?

- [`*-api-client` suffix](https://github.com/Selectra-Dev?utf8=%E2%9C%93&q=php-client&type=&language=) It seems to be the initial way we were calling API clients. We have more clients like that, it would take more time to rename all of them. 
- [`sdk-php-*` prefix](https://github.com/Selectra-Dev?utf8=%E2%9C%93&q=sdk&type=&language=) This convention is used in comparators only. Inspired by [amazon](https://github.com/aws?utf8=%E2%9C%93&q=sdk&type=&language=), [Facebook](https://github.com/facebook?utf8=%E2%9C%93&q=sdk&type=&language=), etc. - the "big ones". Unfortunately, I've noticed first naming convention too late, but here I'm to clear this up. Advantage of this convention over the first one is that this is more *versatile*. You might need the constants and interfaces only, but not necessarily to call the API itself.

**Comment by Haru0** [comment]
_Due to the assignees limit, I'm also inviting @jorgecar, @elrogue, @theosuja, @wilsonelwilson to join the discussion__

**Comment by lord-enzo** [comment]
I guess the second option seems clearer at first glance

**Comment by Haru0** [comment]
_And anybody else who might be interested @Selectra-Dev/developers _

**Comment by VictorBersy** [comment]
I don't think API and SDK are interchangeable names. They have different meaning and purposes. 
An SDK is a development kit, including documentation, libraries, tools and code examples, etc... It's a complete kit for developers to build for a platform. 

While an API is a smaller set of the SDK, it's usually a client to interact with it that is documented.

In our case, I think most - if not all - are just API client.

- https://softwareengineering.stackexchange.com/questions/101873/whats-the-difference-between-an-api-and-an-sdk
- https://stackoverflow.com/questions/834763/difference-between-an-api-and-sdk

**Comment by Haru0** [comment]
@VictorBersy Thank you so much for referencing those discussions.

I have a feeling there is disagreement in the community and inconsistency between "API ~~Client~~" and "API **Client**". People talk about clients one time, other time about documented service (like it was a server). Anyway, those discussions gave me a wider look at this.

Indeed, we use our libraries as API **Clients**. I'm convinced they all should be suffixed with `*-api-client`. It seems only those from comparators could apply for SDK as they expose constants that are used for deeper integration.

Should we use both names then? What exactly should we consider a thing that makes a client an SDK? Should we call SDK every client that exposes more public methods than direct API calls and config setters?

**Comment by rbsteiner** [comment]
I really don't have any high opinion on this... I would prefer using the *-api-client for the sake of simplicity...

**Comment by VictorBersy** [comment]
>  It seems only those from comparators could apply for SDK as they expose constants that are used for deeper integration.
Do they exists yet? Can you give some example?

I don't think constants are enough to make it an SDK IMO

**Comment by Haru0** [comment]
> I don't think constants are enough to make it an SDK IMO.

Understand. Do you think you could briefly explain what are the indicators that make them SDK (something like "if your library fires events or allows for dependency injection - it's supposed to be called SDK")? We could put that into our guidelines/standards.

**Comment by VictorBersy** [comment]
I think an easy way to easily make the difference between an SDK and a API client is that, if this "package" includes useful tools to work with (debugger, view generator for a specific framework,  unit tests helper, integrating easily with a specific part of the framework like ActionMailer for Rails, etc...) then it's a SDK. Otherwise, it's just an API client.

**Comment by Haru0** [comment]
@VictorBersy I'd love to have this description in this repository. Do you think you could propose a small pull request?

Currently, I think this fits `project-management` directory, but we can later move it into a more suitable place.
