### ISSUE TITLE
Use strict_types and final keyword

### ISSUE THREAD

**Issue by JesusValera** [Selectra-Dev/standards#9]
Hi guys,
I create a Pull Request a few days ago but it looks like you have not seen the notification, so, I am going to spam it once. :)

I would like to hear your impressions about the changes I make. 

The PR is: https://github.com/Selectra-Dev/selectra-standards/pull/7
Ty!

**Comment by JesusValera** [comment]
Due to the assignees limit, I am going to write to the other people here to join the discussion.
@Haru0 @jorgecar @theosuja @wilsonelwilson

**Comment by Haru0** [comment]
@lord-enzo , you won! Please let us know what do you think.

**Comment by JesusValera** [comment]
Answering the @Mexidense question about the problems of using or not final classes.
That is a dummy example and I also know that there are better approaches, but it is just an example. :) 

We have the following code:

```php
// foo/bar/Worker.php
class Worker 
{
    public function work()
    {
        dd('Working hard.');
    }
}

// foo/bizz/Person.php
class Person extends Worker {
}

// foo/bizz/Robot.php
class Robot extends Worker {
}
```
Now, let's imagine we want to add the method ```sleep()``` to the parent class ```Worker```, we would been adding the method also to ```Robot```.
If we had the Worker class final, we can modify the class without problems because we are sure there are no child classes and we won't break anything.

For sure, a better implementation could be creating a ```Workable``` interface and we never have to deal with this kind of 'problems' but that is the idea.

**Comment by Mexidense** [comment]
Ok, yes, yes, I understand how to work final classes but I don't understand your example because I thought than you was using it for parent class and not... 

IMHO, we should use always interfaces and use interface with just one responsibility or kind of responsibility :smiley: 

thank you for the clarification :+1:

**Comment by Eighke** [comment]
It's currently more about "Composition vs Inheritance", `final` make Composition mandatory and remove all way to use Inheritance.

It's discute since quite long...  you can find a post from 1998 (Java) already explaining both :

https://www.javaworld.com/article/2076814/inheritance-versus-composition--which-one-should-you-choose-.html

You can search on Google `Composition vs Inheritance`, you probably have a lot of articles on it. :)

**Comment by Haru0** [comment]
Seems like we don't want `strict_types` to be a part of our standards. What should we do with `final` keyword then?

From some reason, there are no tutorials, Laravel documentation that encourage developers to so so. Why?

**Comment by JesusValera** [comment]
I still thinking both things are really handy.

I am going to paste a text my brother shared with me about `strict_types` and `final` keyword.

Strict types
==
Being aware that we are using ~~one of the latest  PHP version (7.2)~~ _7.1 PHP version_, we should also know the potential that it brings to us. We can specify the parameters types and even specify the return value (even `void` for non-return value).

We **SHOULD** write at the top of each PHP file

```php
<?php

declare(strict_types=1);
```
By doing this, we will force our PHP classes to be more correct and self-documenting. By default, scalar type-declarations are non-strict, which means they will attempt to change the original type to match the type specified by the type-declaration.

We **MUST** write, whenever is possible, the types for every parameter and returning value per function. Therefore, we should avoid writing unnecessary PHPDoc which duplicate the information already given by the real code.

## Bad
```php
/**
 * @var string $foo 
 * @var int $bar
 *
 * @return void
 */
public function doSomeAction($foo, $bar)
{
    // ...
}
```

## Good
```php
// NOTICE: No PHPDoc is really necesary because the code is already self-documented
public function doSomeAction(string $foo, int $bar): void
{
    // ...
}
```
## Disclaimer
Adding `declare(strict_types=1)` for existing files **should be avoided** unless they are thoroughly tested. It's because we often receive numbers as strings from external sources (AfterShip/Tracker, REST APIs). These are properly working cases as of today and unless you explicitly cast them to their primitive type it can cause future Fatal Errors.

---

I invite you to read the links I shared before related to this topic, those are really interesting:
https://stackoverflow.com/questions/48723637/what-does-strict-types-do-in-php
https://thevaluable.dev/typing-with-php-7-what-you-shouldnt-do/

**Comment by JesusValera** [comment]
Final classes
==
The same, I recommend you to read those two articles.
I guess you can find more articles defending the use of `final` classes in PHP.

https://ocramius.github.io/blog/when-to-declare-classes-final/
https://matthiasnoback.nl/2018/09/final-classes-by-default-why/

---
> In fact, the second link, at the end of the article says:

## "My mocking tool doesn't work with final classes"
One objection against final classes that I've often heard is: "I like what you say, but my mocking tool doesn't work with final classes". Indeed, most don't. It makes sense, because the test doubles that such a tool generates usually look something like this:

```php
final class CanNotBeExtended
{
}

// This produces a Fatal error:

class TestDoubleForCanNotBeExtended32789473246324369823903 extends CanNotBeExtended
{
    // override implementations of parent class here...
}
```

It's unfortunate, but the tools are not to blame. They'd have to do some sneaky things like hooking into the class loader to make the class non-final (in fact, that's quite doable). But they don't, so the truth gets slapped in our face. All that the tool is saying is that a final class can't be extended - there's nothing problematic about that fatal error. Instead, whenever we feel the need to replace a final class with a test double, we should consider two options:

1. Maybe we shouldn't want to replace the real thing, i.e. the class.
2. Maybe we should introduce something we can replace, i.e. an interface.

Option 1 is often useful when you're trying to mock things like entities and value objects. Just don't do it.

Option 2 should be applied in most other cases. When the class should've had an interface, add one, and create a test double for the interface instead.

**Comment by Eighke** [comment]
> From some reason, there are no tutorials, Laravel documentation that encourage developers to so so. Why?

It should not be Laravel that told you what to use. Laravel give you the choice to use both `Composition` and `Inheritance`.

>  What should we do with final keyword then?

I guess it should be `recommended` for project only (but not mandatory) because it make sense here.

--------------------

> Adding `declare(strict_types=1)` for existing files **should be avoided** unless they are thoroughly tested. It's because we often receive numbers as strings from external sources (AfterShip/Tracker, REST APIs). These are properly working cases as of today and unless you explicitly cast them to their primitive type it can cause future Fatal Errors.

Agreed, it is a BC break, if added on existing files, it should be only on new major version release.
